<?php

$finder                                                    = PhpCsFixer\Finder::create()
    ->exclude('storage')
    ->exclude('vendor')
    ->in(__DIR__);

return PhpCsFixer\Config::create()
    ->setRules([
        '@PSR2'                                           => true,
        'align_multiline_comment'                         => [
            'comment_type'                                => 'phpdocs_only',
        ],
        'array_syntax'                                    => [
            'syntax'                                      => 'short',
        ],
        'backtick_to_shell_exec'                          => true,
        'binary_operator_spaces'                          => [
            'default'                                     => 'align_single_space',
        ],
        'blank_line_after_opening_tag'                    => true,
        'blank_line_after_opening_tag'                    => true,
        'blank_line_before_return'                        => true,
        'blank_line_before_statement'                     => [
            'statements'                                  => [
                'break',
                'continue',
                'declare',
                'return',
                'throw',
                'try',
            ],
        ],
        'braces'                                          => [
            'allow_single_line_closure'                   => false,
            'position_after_anonymous_constructs'         => 'same',
            'position_after_control_structures'           => 'same',
            'position_after_functions_and_oop_constructs' => 'next',
        ],
        'cast_spaces'                                     => true,
        'class_attributes_separation'                     => [
            'elements'                                    => [
                'const',
                'method',
                'property',
            ],
        ],
        'class_definition'                                => [
            'multiLineExtendsEachSingleLine'              => false,
            'singleItemSingleLine'                        => false,
            'singleLine'                                  => true,
        ],
        'class_keyword_remove'                            => false,
        'combine_consecutive_issets'                      => true,
        'combine_consecutive_unsets'                      => true,
        'compact_nullable_typehint'                       => true,
        'concat_space'                                    => [
            'spacing'                                     => 'none',
        ],
        'declare_equal_normalize'                         => [
            'space'                                       => 'none',
        ],
        // 'declare_strict_types'                         => true,
        'dir_constant'                                    => true,
        'doctrine_annotation_array_assignment'            => [],
        'doctrine_annotation_braces'                      => [],
        'doctrine_annotation_indentation'                 => [],
        'doctrine_annotation_spaces'                      => [],
        'elseif'                                          => true,
        'encoding'                                        => true,
        'ereg_to_preg'                                    => true,
        'escape_implicit_backslashes'                     => [
            'double_quoted'                               => true,
            'heredoc_syntax'                              => true,
            'single_quoted'                               => false,
        ],
        'explicit_indirect_variable'                      => true,
        'explicit_string_variable'                        => true,
        'full_opening_tag'                                => true,
        'function_declaration'                            => [
            'closure_function_spacing'                    => 'one',
        ],
        'function_typehint_space'                         => true,
        'general_phpdoc_annotation_remove'                => [
            'annotations'                                 => [],
        ],
        // 'header_comment'                               => [
        //     'commentType'                              => 'PHPDoc',
        //     'header'                                   => ''
        // ],
        'heredoc_to_nowdoc'                               => true,
        'include'                                         => true,
        'increment_style'                                 => [
            'style'                                       => 'pre',
        ],
        'indentation_type'                                => true,
        'is_null'                                         => true,
        'line_ending'                                     => true,
        'linebreak_after_opening_tag'                     => true,
        'list_syntax'                                     => [
            'syntax'                                      => 'long',
        ],
        'lowercase_cast'                                  => true,
        'lowercase_constants'                             => true,
        'lowercase_keywords'                              => true,
        'magic_constant_casing'                           => true,
        'mb_str_functions'                                => true,
        'method_argument_space'                           => [
            'ensure_fully_multiline'                      => false,
            'keep_multiple_spaces_after_comma'            => false,
        ],
        'method_chaining_indentation'                     => true,
        'modernize_types_casting'                         => true,
        'multiline_comment_opening_closing'               => true,
        'multiline_whitespace_before_semicolons'          => [
            'strategy'                                    => 'no_multi_line',
        ],
        'native_function_casing'                          => true,
        // 'native_function_invocation'                   => [
        //     'exclude'                                  => [],
        // ],
        'new_with_braces'                                 => true,
        'no_alias_functions'                              => true,
        'no_blank_lines_after_class_opening'              => true,
        'no_blank_lines_after_phpdoc'                     => true,
        'no_blank_lines_before_namespace'                 => false,
        'no_break_comment'                                => [
            'comment_text'                                => 'no break',
        ],
        'no_closing_tag'                                  => true,
        'no_empty_comment'                                => true,
        'no_empty_phpdoc'                                 => true,
        'no_empty_statement'                              => true,
        'no_extra_blank_lines'                            => true,
        'no_homoglyph_names'                              => true,
        'no_leading_import_slash'                         => true,
        'no_leading_namespace_whitespace'                 => true,
        'no_mixed_echo_print'                             => [
            'use'                                         => 'echo',
        ],
        'no_multiline_whitespace_around_double_arrow'     => true,
        'no_null_property_initialization'                 => true,
        'no_php4_constructor'                             => true,
        'no_short_bool_cast'                              => true,
        'no_short_echo_tag'                               => false,
        'no_singleline_whitespace_before_semicolons'      => true,
        'no_spaces_after_function_name'                   => true,
        'no_spaces_around_offset'                         => true,
        'no_spaces_inside_parenthesis'                    => true,
        'no_superfluous_elseif'                           => true,
        'no_trailing_comma_in_list_call'                  => true,
        'no_trailing_comma_in_singleline_array'           => true,
        'no_trailing_whitespace'                          => true,
        'no_trailing_whitespace_in_comment'               => true,
        'no_unneeded_control_parentheses'                 => [
            'statements'                                  => [
                'break',
                'clone',
                'continue',
                'echo_print',
                'return',
                'switch_case',
                'yield',
            ],
        ],
        'no_unneeded_curly_braces'                        => true,
        'no_unneeded_final_method'                        => true,
        'no_unreachable_default_argument_value'           => true,
        'no_unused_imports'                               => true,
        'no_useless_else'                                 => true,
        'no_useless_return'                               => true,
        'no_whitespace_before_comma_in_array'             => true,
        'no_whitespace_in_blank_line'                     => true,
        'non_printable_character'                         => [
            'use_escape_sequences_in_strings'             => false,
        ],
        'normalize_index_brace'                           => true,
        'not_operator_with_space'                         => false,
        'not_operator_with_successor_space'               => false,
        'object_operator_without_whitespace'              => true,
        'ordered_class_elements'                          => [
            'order'                                       => [
                'use_trait',
                'constant_public', 'constant_protected', 'constant_private',
                'property_public', 'property_protected', 'property_private',
                'construct', 'destruct', 'magic', 'phpunit',
                'method_public', 'method_protected', 'method_private',
            ],
        ],
        'ordered_imports'                                 => [
            'importsOrder'                                => null,
            'sortAlgorithm'                               => 'alpha',
        ],
        'php_unit_construct'                              => true,
        'php_unit_dedicate_assert'                        => [
            'functions'                                   => null,
        ],
        'php_unit_expectation'                            => [
            'target'                                      => 'newest',
        ],
        'php_unit_fqcn_annotation'                        => true,
        'php_unit_mock'                                   => [
            'target'                                      => 'newest',
        ],
        'php_unit_namespaced'                             => [
            'target'                                      => 'newest',
        ],
        'php_unit_no_expectation_annotation'              => [
            'target'                                      => 'newest',
        ],
        'php_unit_strict'                                 => [
            'assertions'                                  => [
                'assertAttributeEquals',
                'assertAttributeNotEquals',
                'assertEquals',
                'assertNotEquals',
            ],
        ],
        'php_unit_test_annotation'                        => [
            'case'                                        => 'snake',
            'style'                                       => 'annotation',
        ],
        'php_unit_test_class_requires_covers'             => false,
        'phpdoc_add_missing_param_annotation'             => [
            'only_untyped'                                => true,
        ],
        'phpdoc_align'                                    => [
            'tags'                                        => [
                'param',
                'return',
                'throws',
                'type',
                'var',
            ],
        ],
        'phpdoc_annotation_without_dot'                   => true,
        'phpdoc_indent'                                   => true,
        'phpdoc_inline_tag'                               => true,
        'phpdoc_no_access'                                => true,
        'phpdoc_no_alias_tag'                             => [
            'replacements'                                => [
                'property-read'                           => 'property',
                'property-write'                          => 'property',
                'type'                                    => 'var',
                'link'                                    => 'see',
            ],
        ],
        'phpdoc_no_empty_return'                          => false,
        'phpdoc_no_package'                               => true,
        'phpdoc_no_useless_inheritdoc'                    => true,
        'phpdoc_order'                                    => true,
        'phpdoc_return_self_reference'                    => [
            'this'                                        => '$this',
            '@this'                                       => '$this',
            '$self'                                       => 'self',
            '@self'                                       => 'self',
            '$static'                                     => 'static',
            '@static'                                     => 'static',
        ],
        'phpdoc_scalar'                                   => true,
        'phpdoc_separation'                               => true,
        'phpdoc_single_line_var_spacing'                  => true,
        'phpdoc_summary'                                  => false,
        'phpdoc_to_comment'                               => true,
        'phpdoc_trim'                                     => true,
        'phpdoc_types'                                    => true,
        'phpdoc_types_order'                              => [
            'null_adjustment'                             => 'always_first',
            'sort_algorithm'                              => 'alpha',
        ],
        'phpdoc_var_without_name'                         => true,
        'pow_to_exponentiation'                           => true,
        'pre_increment'                                   => true,
        'protected_to_private'                            => true,
        'psr0'                                            => false,
        'psr4'                                            => true,
        'random_api_migration'                            => true,
        'return_type_declaration'                         => [
            'space_before'                                => 'none',
        ],
        'self_accessor'                                   => true,
        'semicolon_after_instruction'                     => true,
        'short_scalar_cast'                               => true,
        'simplified_null_return'                          => true,
        'single_blank_line_at_eof'                        => true,
        'single_blank_line_before_namespace'              => true,
        'single_class_element_per_statement'              => [
            'elements'                                    => [
                'const',
                'property',
            ],
        ],
        'single_line_after_imports'                       => true,
        'single_line_comment_style'                       => false,
        'single_quote'                                    => true,
        'space_after_semicolon'                           => [
            'remove_in_empty_for_expressions'             => false,
        ],
        'standardize_not_equals'                          => true,
        'static_lambda'                                   => false,
        'strict_comparison'                               => true,
        'strict_param'                                    => true,
        'switch_case_semicolon_to_colon'                  => true,
        'switch_case_space'                               => true,
        'ternary_operator_spaces'                         => true,
        'ternary_to_null_coalescing'                      => true,
        'trailing_comma_in_multiline_array'               => true,
        'trim_array_spaces'                               => true,
            'unary_operator_spaces'                       => true,
        'visibility_required'                             => [
            'elements'                                    => [
                'property', 'method',
            ],
        ],
        'void_return'                                     => false,
        'whitespace_after_comma_in_array'                 => true,
        'yoda_style'                                      => [
            'equal'                                       => true,
            'identical'                                   => true,
            'less_and_greater'                            => true,
        ],
    ])
    ->setFinder($finder);
